### ISSUE TITLE
OpenAPI 4.3.1 not able to generate anyOf models

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/nlp-sandbox-data-node-i2b2-2014#77]
This issue is still open: https://github.com/OpenAPITools/openapi-generator/issues/7815

This PR merge is more recent than the latest release. Try using the master version of the generator.

**Comment by tschaffter** [comment]
The issue remains when using the version in the branch master. The issue is that the generator does not generate the model `models.any_of_stored_annotation_stored_date_annotation`.

```
$ python -m openapi_server
Traceback (most recent call last):
  File "/home/tschaffter/.conda/envs/data-node-redesign/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/tschaffter/.conda/envs/data-node-redesign/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/c/Users/thoma/Documents/dev/nlp-sandbox-data-node-i2b2-2014/server/openapi_server/__main__.py", line 5, in <module>
    from openapi_server import encoder
  File "/mnt/c/Users/thoma/Documents/dev/nlp-sandbox-data-node-i2b2-2014/server/openapi_server/encoder.py", line 4, in <module>
    from openapi_server.models.base_model_ import Model
  File "/mnt/c/Users/thoma/Documents/dev/nlp-sandbox-data-node-i2b2-2014/server/openapi_server/models/__init__.py", line 18, in <module>
    from openapi_server.models.page_of_annotations import PageOfAnnotations
  File "/mnt/c/Users/thoma/Documents/dev/nlp-sandbox-data-node-i2b2-2014/server/openapi_server/models/page_of_annotations.py", line 9, in <module>
    from openapi_server.models.any_of_stored_annotation_stored_date_annotation import AnyOfStoredAnnotationStoredDateAnnotation
ModuleNotFoundError: No module named 'openapi_server.models.any_of_stored_annotation_stored_date_annotation'
```

If I don't find an example somewhere of what this model could look like, I may change the API to prevent the usage of `oneOf`.

**Comment by tschaffter** [comment]
I tried:

```
$ docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli:latest --version
openapi-generator-cli 5.0.0-SNAPSHOT
  commit : 08fb590
  built  : 2020-11-07T03:38:40Z
  source : https://github.com/openapitools/openapi-generator
  docs   : https://openapi-generator.tech/
$ docker run --rm -v ${PWD}:/local openapitools/openapi-generator-cli:latest generate --input-spec /local/dist.yaml --generator-name python-flask --output /local/server
```

**Comment by tschaffter** [comment]
Recently I start to walk away from using anyOf. It is in general preferable to have properties that are assigned one schema.
